"""empty message

Revision ID: 1582546580ef
Revises: f57fed139686
Create Date: 2019-09-25 10:30:39.536059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1582546580ef'
down_revision = 'f57fed139686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course_sections', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'students', ['name'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'schedules', ['date'], ['id'])
    op.create_foreign_key(None, 'schedules', 'teachers', ['teacher'], ['id'])
    op.create_foreign_key(None, 'schedules', 'course_sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'subjects', ['subject_id'], ['id'])
    op.drop_column('schedules', 'course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('course', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'course_sections', type_='foreignkey')
    # ### end Alembic commands ###
