"""empty message

Revision ID: 4c950d224507
Revises: 662e704c257c
Create Date: 2019-09-24 13:26:35.168521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c950d224507'
down_revision = '662e704c257c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course_sections', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'schedules', ['date'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'students', ['name'], ['id'])
    op.drop_column('enrollments', 'term')
    op.add_column('schedules', sa.Column('term', sa.String(length=45), nullable=True))
    op.create_foreign_key(None, 'schedules', 'course_sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'teachers', ['teacher'], ['id'])
    op.create_foreign_key(None, 'schedules', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'courses', ['course'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'term')
    op.add_column('enrollments', sa.Column('term', mysql.VARCHAR(length=45), nullable=False))
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'course_sections', type_='foreignkey')
    # ### end Alembic commands ###
