"""empty message

Revision ID: 662e704c257c
Revises: 
Create Date: 2019-09-24 11:57:39.008975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662e704c257c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=45), nullable=False),
    sa.Column('end', sa.String(length=45), nullable=False),
    sa.Column('day', sa.String(length=45), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'course_sections', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'schedules', ['date'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'students', ['name'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'course_sections', type_='foreignkey')
    op.drop_table('schedules')
    # ### end Alembic commands ###
