"""empty message

Revision ID: 83ae9bf38b03
Revises: d2072df0fef1
Create Date: 2019-09-26 10:59:03.168396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ae9bf38b03'
down_revision = 'd2072df0fef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'course_sections', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'schedules', ['schedule_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'teachers', ['teacher'], ['id'])
    op.create_foreign_key(None, 'schedules', 'course_sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'course_sections', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
