"""empty message

Revision ID: d2072df0fef1
Revises: 1582546580ef
Create Date: 2019-09-25 10:40:29.861349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2072df0fef1'
down_revision = '1582546580ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course_sections', 'courses', ['course_id'], ['id'])
    op.add_column('enrollments', sa.Column('schedule_id', sa.String(length=45), nullable=True))
    op.add_column('enrollments', sa.Column('student_id', sa.String(length=45), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'schedules', ['schedule_id'], ['id'])
    op.drop_column('enrollments', 'date')
    op.drop_column('enrollments', 'name')
    op.create_foreign_key(None, 'schedules', 'course_sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'schedules', 'teachers', ['teacher'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.add_column('enrollments', sa.Column('name', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('enrollments', sa.Column('date', mysql.VARCHAR(length=45), nullable=True))
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'student_id')
    op.drop_column('enrollments', 'schedule_id')
    op.drop_constraint(None, 'course_sections', type_='foreignkey')
    # ### end Alembic commands ###
